apiVersion: v1
kind: Service
metadata:
  name: conference-service
spec:
  type: NodePort
  selector:
    app: conference-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008 # Access via http://<node-ip>:30008
